name: gallery_picker_plus
description: Modern, customizable gallery picker for Flutter with multi-select, recent media, hero transitions, builder-based customization, and album/category views.
version: 0.0.1+1

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  photo_gallery:
    git:
      url: https://github.com/abdelrahman-abied/photo_gallery.git

  file_picker: ^10.1.2
  permission_handler: ^12.0.1
  transparent_image: ^2.0.1
  video_player: ^2.8.2
  device_info_plus: ^12.2.0
  get: ^4.6.6
  video_thumbnail: ^0.5.3
#  video_thumbnail:
#    git:
#      url: https://github.com/zeelbhanderi/video_thumbnail.git

  intl: ^0.20.2
  page_transition: ^2.1.0
  bottom_sheet_scaffold: ^0.1.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This package provides Flutter widgets/utilities only; no native plugin registration required.
  # If you later add platform code, re-introduce the plugin.platforms section per Flutter docs.
  # (Do not add an empty plugin/platforms block; it breaks pubspec validation.)
